"""
playlists.py
------------
Handles all playlist operations against the Spotify API:
  - Fetching the user's existing playlists
  - Creating new playlists
  - Retrieving the track URIs already in a playlist
  - Adding tracks while skipping duplicates
  - Removing tracks that are no longer in the user's liked songs
"""

from typing import Any

import spotipy


# Spotify allows at most 100 track URIs per add/remove request
_BATCH_SIZE = 100

# Maximum number of playlists / tracks returned per API page
_PAGE_LIMIT = 50


def get_user_playlists(
    sp: spotipy.Spotify,
    username: str,
) -> dict[str, str]:
    """
    Return all playlists owned by *username* as a {name: playlist_id} dict.

    Only playlists whose owner matches *username* are included, so
    playlists the user follows (but does not own) are excluded.

    Args:
        sp:       Authenticated spotipy client.
        username: Spotify user ID (from secrets file).

    Returns:
        Dict mapping playlist name -> playlist ID.
    """
    playlists: dict[str, str] = {}
    offset = 0

    while True:
        page = sp.current_user_playlists(limit=_PAGE_LIMIT, offset=offset)
        items = page.get("items", [])

        if not items:
            break

        for pl in items:
            if pl["owner"]["id"] == username:
                playlists[pl["name"]] = pl["id"]

        # Do NOT use page["next"] -- since the February 2026 API changes,
        # that URL points to the removed /users/{id}/playlists endpoint.
        # Use manual offset-based pagination instead.
        if len(items) < _PAGE_LIMIT:
            break

        offset += _PAGE_LIMIT

    return playlists


def get_playlist_track_uris(
    sp: spotipy.Spotify,
    playlist_id: str,
) -> set[str]:
    """
    Return the set of track URIs currently in *playlist_id*.

    Used to detect duplicates before adding new tracks, and to find
    tracks that should be removed.

    Args:
        sp:          Authenticated spotipy client.
        playlist_id: Spotify playlist ID.

    Returns:
        Set of track URI strings (e.g. 'spotify:track:...').
    """
    uris: set[str] = set()
    offset = 0

    while True:
        page = sp.playlist_items(
            playlist_id,
            fields="items(track(uri)),next",
            limit=_PAGE_LIMIT,
            offset=offset,
        )
        items = page.get("items", [])

        if not items:
            break

        for item in items:
            track = item.get("track")
            if track and track.get("uri"):
                uris.add(track["uri"])

        if page["next"] is None:
            break

        offset += _PAGE_LIMIT

    return uris


def find_or_create_playlist(
    sp: spotipy.Spotify,
    username: str,
    name: str,
    existing_playlists: dict[str, str],
    public: bool = True,
) -> tuple[str, bool]:
    """
    Return the ID of a playlist with the given *name*, creating it if needed.

    Args:
        sp:                 Authenticated spotipy client.
        username:           Spotify user ID (kept for API compatibility).
        name:               Desired playlist name.
        existing_playlists: Dict returned by get_user_playlists (modified in-place
                            when a new playlist is created).
        public:             Whether newly created playlists should be public.

    Returns:
        Tuple (playlist_id, was_created) where was_created is True when a
        new playlist was created in this call.
    """
    if name in existing_playlists:
        return existing_playlists[name], False

    # POST /users/{id}/playlists was removed in the February 2026 Spotify API
    # changes. We now call POST /me/playlists directly.
    new_pl = sp._post(
        "me/playlists",
        payload={
            "name": name,
            "public": public,
            "description": "Auto-generated by Spotify Playlister",
        },
    )
    playlist_id = new_pl["id"]
    existing_playlists[name] = playlist_id
    return playlist_id, True


def add_tracks_without_duplicates(
    sp: spotipy.Spotify,
    playlist_id: str,
    track_uris: list[str],
    existing_uris: set[str],
) -> tuple[int, int]:
    """
    Add *track_uris* to the playlist, skipping any already present.

    Tracks are added in batches of up to 100 (Spotify API limit).

    Args:
        sp:            Authenticated spotipy client.
        playlist_id:   Target playlist ID.
        track_uris:    List of Spotify track URIs to potentially add.
        existing_uris: Set of URIs already in the playlist (from
                       get_playlist_track_uris), avoids a redundant API call.

    Returns:
        Tuple (added_count, skipped_count).
    """
    new_uris = [uri for uri in track_uris if uri not in existing_uris]
    skipped  = len(track_uris) - len(new_uris)

    for i in range(0, len(new_uris), _BATCH_SIZE):
        batch = new_uris[i : i + _BATCH_SIZE]
        sp.playlist_add_items(playlist_id, batch)

    return len(new_uris), skipped


def remove_unliked_tracks(
    sp: spotipy.Spotify,
    playlist_id: str,
    target_uris: set[str],
    existing_uris: set[str],
) -> int:
    """
    Remove from the playlist any track no longer in the user's liked songs.

    A track is removed when it is in the playlist (*existing_uris*)
    but NOT in the current set of liked-song URIs for the period
    (*target_uris*).

    Tracks are removed in batches of up to 100 (Spotify API limit).

    Args:
        sp:            Authenticated spotipy client.
        playlist_id:   Target playlist ID.
        target_uris:   URIs that *should* be in the playlist (current liked
                       songs for the period).
        existing_uris: URIs currently in the playlist.

    Returns:
        Number of tracks removed.
    """
    to_remove = list(existing_uris - target_uris)

    for i in range(0, len(to_remove), _BATCH_SIZE):
        batch = to_remove[i : i + _BATCH_SIZE]
        sp.playlist_remove_all_occurrences_of_items(playlist_id, batch)

    return len(to_remove)


def sync_period_to_playlist(
    sp: spotipy.Spotify,
    username: str,
    playlist_name: str,
    tracks: list[dict[str, Any]],
    existing_playlists: dict[str, str],
    public: bool = True,
    remove_unliked: bool = True,
    dry_run: bool = False,
) -> dict[str, Any]:
    """
    Ensure a playlist for *playlist_name* exactly mirrors the provided *tracks*:
      - tracks in *tracks* but not in the playlist  -> added
      - tracks in the playlist but not in *tracks*  -> removed (if remove_unliked)
      - tracks already present in both              -> skipped

    Args:
        sp:                 Authenticated spotipy client.
        username:           Spotify user ID.
        playlist_name:      Name of the target playlist.
        tracks:             Track dicts for this period (current liked songs).
        existing_playlists: Running dict of {name: id} (modified in-place).
        public:             Create new playlists as public (default True).
        remove_unliked:     Remove tracks no longer in liked songs (default True).
        dry_run:            Print what would happen but make no API calls.

    Returns:
        Summary dict with keys:
            playlist_name, playlist_id, created, added, skipped, removed.
    """
    target_uris = set(t["track_uri"] for t in tracks)

    if dry_run:
        already_exists = playlist_name in existing_playlists
        print(
            f"  [dry-run] '{playlist_name}': "
            f"{'exists' if already_exists else 'would be created'}, "
            f"{len(target_uris)} track(s) to sync."
        )
        return {
            "playlist_name": playlist_name,
            "playlist_id":   existing_playlists.get(playlist_name, "N/A"),
            "created":        not already_exists,
            "added":          len(target_uris),
            "skipped":        0,
            "removed":        0,
        }

    playlist_id, created = find_or_create_playlist(
        sp, username, playlist_name, existing_playlists, public=public
    )

    # Fetch current playlist contents once; reuse for both add and remove logic
    existing_uris = get_playlist_track_uris(sp, playlist_id)

    added, skipped = add_tracks_without_duplicates(
        sp, playlist_id, list(target_uris), existing_uris
    )

    removed = 0
    if remove_unliked:
        removed = remove_unliked_tracks(
            sp, playlist_id, target_uris, existing_uris
        )

    return {
        "playlist_name": playlist_name,
        "playlist_id":   playlist_id,
        "created":        created,
        "added":          added,
        "skipped":        skipped,
        "removed":        removed,
    }
