"""
playlists.py
------------
Handles all playlist operations against the Spotify API:
  - Fetching the user's existing playlists
  - Creating new playlists
  - Retrieving the ordered track list of a playlist
  - Syncing a playlist to exactly match a target ordered track list,
    preserving the original Liked Songs order and preventing duplicates
"""

from typing import Any

import spotipy


# Spotify allows at most 100 track URIs per add / replace request
_BATCH_SIZE = 100

# Maximum number of playlists / tracks returned per API page
_PAGE_LIMIT = 50


def get_user_playlists(
    sp: spotipy.Spotify,
    username: str,
) -> dict[str, str]:
    """
    Return all playlists owned by *username* as a {name: playlist_id} dict.

    Only playlists whose owner matches *username* are included, so
    playlists the user follows (but does not own) are excluded.

    Args:
        sp:       Authenticated spotipy client.
        username: Spotify user ID (from secrets file).

    Returns:
        Dict mapping playlist name -> playlist ID.
    """
    playlists: dict[str, str] = {}
    offset = 0

    while True:
        page = sp.current_user_playlists(limit=_PAGE_LIMIT, offset=offset)
        items = page.get("items", [])

        if not items:
            break

        for pl in items:
            if pl["owner"]["id"] == username:
                playlists[pl["name"]] = pl["id"]

        # Do NOT use page["next"] -- since the February 2026 API changes,
        # that URL points to the removed /users/{id}/playlists endpoint.
        # Use manual offset-based pagination instead.
        if len(items) < _PAGE_LIMIT:
            break

        offset += _PAGE_LIMIT

    return playlists


def get_playlist_tracks_ordered(
    sp: spotipy.Spotify,
    playlist_id: str,
) -> list[str]:
    """
    Return the track URIs currently in *playlist_id* as an ordered list.

    The list preserves the exact position of each track in the playlist
    (index 0 = first track shown in Spotify). This is used both to detect
    order differences and to know which tracks to remove.

    Returning a list (not a set) is intentional: order matters here.

    Args:
        sp:          Authenticated spotipy client.
        playlist_id: Spotify playlist ID.

    Returns:
        Ordered list of track URI strings (e.g. 'spotify:track:...').
    """
    uris: list[str] = []
    offset = 0

    while True:
        page = sp.playlist_items(
            playlist_id,
            fields="items(track(uri)),next",
            limit=_PAGE_LIMIT,
            offset=offset,
        )
        items = page.get("items", [])

        if not items:
            break

        for item in items:
            track = item.get("track")
            if track and track.get("uri"):
                uris.append(track["uri"])

        if page["next"] is None:
            break

        offset += _PAGE_LIMIT

    return uris


def find_or_create_playlist(
    sp: spotipy.Spotify,
    username: str,
    name: str,
    existing_playlists: dict[str, str],
    public: bool = True,
) -> tuple[str, bool]:
    """
    Return the ID of a playlist with the given *name*, creating it if needed.

    Args:
        sp:                 Authenticated spotipy client.
        username:           Spotify user ID (kept for API compatibility).
        name:               Desired playlist name.
        existing_playlists: Dict returned by get_user_playlists (modified in-place
                            when a new playlist is created).
        public:             Whether newly created playlists should be public.

    Returns:
        Tuple (playlist_id, was_created) where was_created is True when a
        new playlist was created in this call.
    """
    if name in existing_playlists:
        return existing_playlists[name], False

    # POST /users/{id}/playlists was removed in the February 2026 Spotify API
    # changes. We now call POST /me/playlists directly.
    new_pl = sp._post(
        "me/playlists",
        payload={
            "name": name,
            "public": public,
            "description": "Auto-generated by Spotify Playlister",
        },
    )
    playlist_id = new_pl["id"]
    existing_playlists[name] = playlist_id
    return playlist_id, True


def replace_playlist_contents(
    sp: spotipy.Spotify,
    playlist_id: str,
    ordered_uris: list[str],
) -> None:
    """
    Atomically replace the entire contents of a playlist with *ordered_uris*.

    Spotify's replace endpoint accepts at most 100 URIs and clears the
    playlist before writing. For lists longer than 100 tracks, the first
    batch replaces (clearing old content), then remaining tracks are
    appended in subsequent batches of 100.

    Args:
        sp:           Authenticated spotipy client.
        playlist_id:  Target playlist ID.
        ordered_uris: Complete desired track list in the intended play order.
    """
    if not ordered_uris:
        # Clear the playlist entirely
        sp.playlist_replace_items(playlist_id, [])
        return

    # First batch: replaces ALL existing content atomically (no leftover tracks)
    sp.playlist_replace_items(playlist_id, ordered_uris[:_BATCH_SIZE])

    # Subsequent batches: append the remaining tracks in order
    for i in range(_BATCH_SIZE, len(ordered_uris), _BATCH_SIZE):
        batch = ordered_uris[i : i + _BATCH_SIZE]
        sp.playlist_add_items(playlist_id, batch)


def sync_period_to_playlist(
    sp: spotipy.Spotify,
    username: str,
    playlist_name: str,
    tracks: list[dict[str, Any]],
    existing_playlists: dict[str, str],
    public: bool = True,
    remove_unliked: bool = True,
    dry_run: bool = False,
) -> dict[str, Any]:
    """
    Ensure a playlist exactly mirrors *tracks* in the correct order.

    Strategy:
      1. Build the desired ordered URI list from *tracks* (never convert to
         a set, so order is always preserved).
      2. Fetch the playlist's current contents as an ordered list.
      3. If current == desired (same URIs, same order) → do nothing (fast path).
      4. If anything differs (new tracks, unliked tracks, wrong order) →
         replace the entire playlist atomically via replace_playlist_contents.

    This approach simultaneously solves:
      - Duplicates: replacing the whole playlist is idempotent by definition.
      - Order:      the final playlist always matches the target list exactly.

    Args:
        sp:                 Authenticated spotipy client.
        username:           Spotify user ID.
        playlist_name:      Name of the target playlist.
        tracks:             Track dicts for this period, ordered newest-first
                            (as produced by tracks.get_saved_tracks).
        existing_playlists: Running dict of {name: id} (modified in-place).
        public:             Create new playlists as public (default True).
        remove_unliked:     Remove tracks no longer in liked songs (default True).
        dry_run:            Print what would happen but make no API calls.

    Returns:
        Summary dict with keys:
            playlist_name, playlist_id, created, added, skipped, removed, reordered.
    """
    # Build the desired ordered URI list.
    # NEVER convert to a set here -- that would destroy the order.
    target_uris: list[str] = [t["track_uri"] for t in tracks]
    target_set:  set[str]  = set(target_uris)

    if dry_run:
        already_exists = playlist_name in existing_playlists
        print(
            f"  [dry-run] '{playlist_name}': "
            f"{'exists' if already_exists else 'would be created'}, "
            f"{len(target_uris)} track(s) to sync."
        )
        return {
            "playlist_name": playlist_name,
            "playlist_id":   existing_playlists.get(playlist_name, "N/A"),
            "created":        not already_exists,
            "added":          len(target_uris),
            "skipped":        0,
            "removed":        0,
            "reordered":      False,
        }

    playlist_id, created = find_or_create_playlist(
        sp, username, playlist_name, existing_playlists, public=public
    )

    # Fetch current playlist as an ordered list (NOT a set).
    current_uris: list[str] = get_playlist_tracks_ordered(sp, playlist_id)
    current_set:  set[str]  = set(current_uris)

    # Compute the effective target list based on the remove_unliked flag.
    # If remove_unliked is False, keep tracks already in the playlist that
    # are not in this period's liked songs (append them after the target tracks).
    if remove_unliked:
        effective_uris = target_uris
    else:
        extra = [u for u in current_uris if u not in target_set]
        effective_uris = target_uris + extra

    # Fast path: if the playlist already matches exactly, nothing to do.
    if current_uris == effective_uris:
        return {
            "playlist_name": playlist_name,
            "playlist_id":   playlist_id,
            "created":        created,
            "added":          0,
            "skipped":        len(current_uris),
            "removed":        0,
            "reordered":      False,
        }

    # Compute change stats for the summary report.
    effective_set = set(effective_uris)
    added    = len(effective_set - current_set)
    removed  = len(current_set - effective_set)
    reordered = (current_set == effective_set and current_uris != effective_uris)

    # Replace the entire playlist to guarantee correct content and order.
    # This is idempotent: running it twice produces the same result,
    # which is why re-executing the script never creates duplicates.
    replace_playlist_contents(sp, playlist_id, effective_uris)

    return {
        "playlist_name": playlist_name,
        "playlist_id":   playlist_id,
        "created":        created,
        "added":          added,
        "skipped":        len(current_set & effective_set),
        "removed":        removed,
        "reordered":      reordered,
    }
